run:
  build-tags:
    - nolic
  linters:
    presets:
      - bugs
      - unused
      - format
      - style
    disable:
      - gochecknoglobals
      - gochecknoinits
      - gocritic
      - lll
      - unparam
  tests: true

issues:
  exclude-dirs:
    - api
    - test
