app:
  host: 0.0.0.0
  http-port: 8000
  grpc-port: 8001
  ishttps: false
  yaml: false
src:
  kube-config: ""
  namespace: default
  objects:
    - deployment
    - service
  exclude:
    - abc
  include:
    - *
dst:
  kube-config: /Users/gavinz/.kube/config
  namespace: default
log:
  compress: false
  consolestdout: true
  filestdout: true
  level: debug
  localtime: true
  maxage: 30
  maxbackups: 300
  maxsize: 10240
  path: ./logs/k8sync.log
  jsonformat: false
